-- ============================================================================
-- Costing module — seed from barramundi_costing_v11.xlsx
--
-- GENERATED by packages/engine/scripts/gen-costing-seed.mjs from the committed
-- fixture packages/engine/fixtures/v11.json. Do not hand-edit: regenerate.
--
-- Values are the workbook's own, and the engine reproduces them to a relative
-- 1e-9 (packages/engine/test/costing-parity.test.ts). Two things here are
-- deliberately NOT the workbook:
--   1. The six by-product SKUs ship as raw_material_basis = absorbed
--      (Decisions §7). The other 28 are full_fish and match v11 exactly.
--   2. Per-bucket FCR is the workbook's PLACEHOLDER (v11 flags it as such at
--      cell A22), and per-bucket yields are seeded from each SKU's flat yield.
--      Both are editable and get real farm data later (Decisions §6).
-- ============================================================================

set search_path = demand_planner, public;

-- ---------------------------------------------------------------------------
-- 1. Size buckets — costing's own copy (Decisions §6)
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_size_buckets (org_id, label, min_g, max_g, median_g, fcr, sort_order)
select o.id, b.label, b.min_g, b.max_g, b.median_g, b.fcr, b.sort_order
from demand_planner.organizations o,
     (values
        ('0-600g', 0, 600, 300, 1.1::numeric, 10),
        ('600-800g', 600, 800, 700, 1.25::numeric, 20),
        ('800-1100g', 800, 1100, 950, 1.35::numeric, 30),
        ('1100-1500g', 1100, 1500, 1300, 1.45::numeric, 40),
        ('1500-1800g', 1500, 1800, 1650, 1.55::numeric, 50),
        ('1800-2200g', 1800, 2200, 2000, 1.65::numeric, 60),
        ('2200-4000g', 2200, 4000, 3100, 1.75::numeric, 70)
     ) as b(label, min_g, max_g, median_g, fcr, sort_order)
where o.slug = 'oceanpick'
on conflict (org_id, label) do nothing;

-- ---------------------------------------------------------------------------
-- 2. Destinations — the port list (rates land on the version, below)
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_destinations (org_id, name, sort_order)
select o.id, d.name, d.sort_order
from demand_planner.organizations o,
     (values
        ('Dubai (UAE)', 10),
        ('Singapore', 20),
        ('Doha (Qatar)', 30),
        ('Male (Maldives)', 40),
        ('Hong Kong', 50),
        ('London (UK)', 60),
        ('Sydney (AU)', 70),
        ('New York (US)', 80),
        ('Melbourne (AU)', 90),
        ('Brisbane (AU)', 100),
        ('Perth (AU)', 110),
        ('Adelaide (AU)', 120),
        ('Los Angeles (US)', 130),
        ('Miami (US)', 140),
        ('Amsterdam (NL)', 150)
     ) as d(name, sort_order)
where o.slug = 'oceanpick'
on conflict (org_id, name) do nothing;

-- ---------------------------------------------------------------------------
-- 3. Assumption version 1 — the workbook as at v11 (Decisions §4)
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_assumption_versions (
  org_id, version_no, label, notes, is_current,
  feed_cost_per_kg, clearing_cost_per_kg, fcr_reference, fx_rate,
  import_tax_pct_domestic, import_tax_pct_export,
  domestic_transport_lkr, domestic_cold_hold_lkr,
  export_freight_to_port_usd, export_cold_chain_usd,
  rack_margin_pct, fob_margin_pct,
  importer_clearing_pct, importer_markup_pct, distributor_markup_pct,
  container_fill_kg, air_lot_kg
)
select
  o.id, 1, 'v11 (imported)', 'Imported from barramundi_costing_v11.xlsx', true,
  1.35, 0.05, 1.5, 340,
  0.35, 0,
  60, 40,
  0.1, 0.1,
  0.4, 0.4,
  0.05, 0.1, 0.15,
  7000, 500
from demand_planner.organizations o
where o.slug = 'oceanpick'
on conflict (org_id, version_no) do nothing;

-- ---------------------------------------------------------------------------
-- 4. ODC components (Decisions §3 / handoff §3.2)
--
-- basis drives size-bucket amortisation: per_fish divides by the median
-- weight, per_kg stays flat. v11 hard-codes this; here it is editable.
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_odc_components (version_id, name, value, currency, basis, sort_order)
select v.id, c.name, c.value, c.currency::demand_planner.cost_currency, c.basis::demand_planner.cost_odc_basis, c.sort_order
from demand_planner.cost_assumption_versions v
join demand_planner.organizations o on o.id = v.org_id
cross join (values
        ('fingerling', 0.25::numeric, 'USD', 'per_fish', 10),
        ('transport - trinco/colombo', 19::numeric, 'LKR', 'per_kg', 20),
        ('ice', 12::numeric, 'LKR', 'per_kg', 30),
        ('vaccine', 23.4::numeric, 'LKR', 'per_fish', 40),
        ('additives', 0::numeric, 'USD', 'per_kg', 50),
        ('royalty', 5::numeric, 'LKR', 'per_kg', 60)
     ) as c(name, value, currency, basis, sort_order)
where o.slug = 'oceanpick' and v.version_no = 1
on conflict (version_id, name) do nothing;

-- ---------------------------------------------------------------------------
-- 5. Destination rates for version 1
--
-- Per shipment, not per kg: the engine divides by container_fill_kg /
-- air_lot_kg so changing the fill weight reprices every port at once.
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_destination_rates (version_id, destination_id, sea_rate_per_20ft, air_rate_per_lot)
select v.id, d.id, r.sea, r.air
from demand_planner.cost_assumption_versions v
join demand_planner.organizations o on o.id = v.org_id
join (values
        ('Dubai (UAE)', 3150::numeric, 1400::numeric),
        ('Singapore', 2800::numeric, 1250::numeric),
        ('Doha (Qatar)', 3500::numeric, 1450::numeric),
        ('Male (Maldives)', 2450::numeric, 900::numeric),
        ('Hong Kong', 3150::numeric, 1300::numeric),
        ('London (UK)', 5950::numeric, 2250::numeric),
        ('Sydney (AU)', 4900::numeric, 1900::numeric),
        ('New York (US)', 7700::numeric, 2750::numeric),
        ('Melbourne (AU)', 5200::numeric, 2000::numeric),
        ('Brisbane (AU)', 4800::numeric, 1900::numeric),
        ('Perth (AU)', 4500::numeric, 1850::numeric),
        ('Adelaide (AU)', 5000::numeric, 1950::numeric),
        ('Los Angeles (US)', 6500::numeric, 2400::numeric),
        ('Miami (US)', 7000::numeric, 2600::numeric),
        ('Amsterdam (NL)', 6200::numeric, 2300::numeric)
     ) as r(name, sea, air) on true
join demand_planner.cost_destinations d on d.org_id = o.id and d.name = r.name
where o.slug = 'oceanpick' and v.version_no = 1
on conflict (version_id, destination_id) do nothing;

-- ---------------------------------------------------------------------------
-- 6. SKU master — one list, both markets (Decisions §2)
--
-- process/packing/marinade are USD everywhere; domestic converts at FX.
-- glaze_pct is 0 on every v11 row: glaze is a per-SKU input that drives the
-- "with glaze" output block, not a reason to duplicate a SKU.
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_skus (
  org_id, name, status, category, sort_order, glaze_pct, base_yield,
  pct_fish, pct_marinade, marinade_usd_per_kg, process_usd_per_kg,
  packing_usd_per_kg, pack_size, raw_material_basis
)
select o.id, s.name, s.status::demand_planner.cost_sku_status, s.category, s.sort_order,
       s.glaze_pct, s.base_yield, s.pct_fish, s.pct_marinade,
       s.marinade_usd, s.process_usd, s.packing_usd, s.pack_size,
       s.basis::demand_planner.cost_raw_material_basis
from demand_planner.organizations o,
     (values
        ('Whole round (ungutted)', 'active', 'Whole', 10, 0::numeric, 0.98::numeric, 1::numeric, 0::numeric, 0::numeric, 0.4::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Whole gutted (WG)', 'active', 'Whole', 20, 0::numeric, 0.92::numeric, 1::numeric, 0::numeric, 0::numeric, 0.45::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Whole gilled & gutted (WGG)', 'inactive', 'Whole', 30, 0::numeric, 0.88::numeric, 1::numeric, 0::numeric, 0::numeric, 0.5::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Whole scaled & gutted', 'active', 'Whole', 40, 0::numeric, 0.85::numeric, 1::numeric, 0::numeric, 0::numeric, 0.6::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Steaks / darne (bone-in)', 'active', 'Whole', 50, 0::numeric, 0.82::numeric, 1::numeric, 0::numeric, 0::numeric, 0.45::numeric, 0.3::numeric, '500g', 'full_fish'),
        ('Boat cut', 'inactive', 'Whole', 60, 0::numeric, 0.75::numeric, 1::numeric, 0::numeric, 0::numeric, 0.55::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Butterfly cut', 'inactive', 'Whole', 70, 0::numeric, 0.72::numeric, 1::numeric, 0::numeric, 0::numeric, 0.55::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Skin-on fillet', 'active', 'Fillet', 80, 0::numeric, 0.45::numeric, 1::numeric, 0::numeric, 0::numeric, 1::numeric, 0.3::numeric, null::text, 'full_fish'),
        ('Skinless boneless fillet', 'active', 'Fillet', 90, 0::numeric, 0.38::numeric, 1::numeric, 0::numeric, 0::numeric, 1::numeric, 0.3::numeric, null::text, 'full_fish'),
        ('Skinless fillet — premium trim', 'inactive', 'Fillet', 100, 0::numeric, 0.34::numeric, 1::numeric, 0::numeric, 0::numeric, 1.25::numeric, 0.35::numeric, null::text, 'full_fish'),
        ('Fillet portions — skin-on CC', 'active', 'Fillet', 110, 0::numeric, 0.32::numeric, 1::numeric, 0::numeric, 0::numeric, 1.15::numeric, 0.35::numeric, null::text, 'full_fish'),
        ('Fillet portions — skinless', 'inactive', 'Fillet', 120, 0::numeric, 0.36::numeric, 1::numeric, 0::numeric, 0::numeric, 1.15::numeric, 0.35::numeric, null::text, 'full_fish'),
        ('Tail portions — regular (70/130) s/on', 'active', 'Fillet', 130, 0::numeric, 0.3::numeric, 1::numeric, 0::numeric, 0::numeric, 1.15::numeric, 0.35::numeric, null::text, 'full_fish'),
        ('Tail portions — small (40/70) s/on', 'active', 'Fillet', 140, 0::numeric, 0.28::numeric, 1::numeric, 0::numeric, 0::numeric, 1.2::numeric, 0.35::numeric, null::text, 'full_fish'),
        ('Fish cubes / stir-fry', 'active', 'Fillet', 150, 0::numeric, 0.3::numeric, 1::numeric, 0::numeric, 0::numeric, 1.15::numeric, 0.33::numeric, '500g', 'full_fish'),
        ('Loin portions', 'inactive', 'Fillet', 160, 0::numeric, 0.3::numeric, 1::numeric, 0::numeric, 0::numeric, 1.15::numeric, 0.35::numeric, null::text, 'full_fish'),
        ('Belly flaps', 'active', 'By-product', 170, 0::numeric, 0.06::numeric, 1::numeric, 0::numeric, 0::numeric, 0.2::numeric, 0.3::numeric, null::text, 'absorbed'),
        ('Head', 'inactive', 'By-product', 180, 0::numeric, 0.11::numeric, 1::numeric, 0::numeric, 0::numeric, 0.2::numeric, 0.15::numeric, null::text, 'absorbed'),
        ('Collar', 'inactive', 'By-product', 190, 0::numeric, 0.05::numeric, 1::numeric, 0::numeric, 0::numeric, 0.4::numeric, 0.25::numeric, null::text, 'absorbed'),
        ('Fish frames / bones (stock)', 'inactive', 'By-product', 200, 0::numeric, 0.08::numeric, 1::numeric, 0::numeric, 0::numeric, 0.1::numeric, 0.15::numeric, null::text, 'absorbed'),
        ('Fish skin (crispy / pet treat)', 'inactive', 'By-product', 210, 0::numeric, 0.03::numeric, 1::numeric, 0::numeric, 0::numeric, 0.2::numeric, 0.2::numeric, null::text, 'absorbed'),
        ('Trimmings / mince', 'inactive', 'By-product', 220, 0::numeric, 0.07::numeric, 1::numeric, 0::numeric, 0::numeric, 0.2::numeric, 0.2::numeric, null::text, 'absorbed'),
        ('Marinated fillet — lemon herb', 'inactive', 'Value-added', 230, 0::numeric, 0.38::numeric, 0.82::numeric, 0.18::numeric, 1.8::numeric, 1.4::numeric, 0.45::numeric, null::text, 'full_fish'),
        ('Marinated fillet — hot & spicy', 'inactive', 'Value-added', 240, 0::numeric, 0.38::numeric, 0.82::numeric, 0.18::numeric, 1.6::numeric, 1.4::numeric, 0.45::numeric, null::text, 'full_fish'),
        ('Marinated portions — BBQ', 'inactive', 'Value-added', 250, 0::numeric, 0.36::numeric, 0.8::numeric, 0.2::numeric, 1.7::numeric, 1.3::numeric, 0.45::numeric, null::text, 'full_fish'),
        ('Marinated cubes — curry cut', 'inactive', 'Value-added', 260, 0::numeric, 0.35::numeric, 0.78::numeric, 0.22::numeric, 1.5::numeric, 1.35::numeric, 0.45::numeric, null::text, 'full_fish'),
        ('Teriyaki glazed portions', 'inactive', 'Value-added', 270, 0::numeric, 0.36::numeric, 0.78::numeric, 0.22::numeric, 2.2::numeric, 1.45::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Cajun skin-on fillet', 'inactive', 'Value-added', 280, 0::numeric, 0.45::numeric, 0.85::numeric, 0.15::numeric, 1.9::numeric, 1.2::numeric, 0.45::numeric, null::text, 'full_fish'),
        ('Crumbed / breaded fillet', 'inactive', 'Value-added', 290, 0::numeric, 0.38::numeric, 0.7::numeric, 0.3::numeric, 1.2::numeric, 1.6::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Battered fish fingers', 'inactive', 'Value-added', 300, 0::numeric, 0.35::numeric, 0.65::numeric, 0.35::numeric, 1::numeric, 1.7::numeric, 0.5::numeric, null::text, 'full_fish'),
        ('Fish sausages', 'inactive', 'Value-added', 310, 0::numeric, 0.3::numeric, 0.6::numeric, 0.4::numeric, 0.9::numeric, 1.8::numeric, 0.55::numeric, null::text, 'full_fish'),
        ('Fish meatballs', 'inactive', 'Value-added', 320, 0::numeric, 0.3::numeric, 0.62::numeric, 0.38::numeric, 0.95::numeric, 1.75::numeric, 0.55::numeric, null::text, 'full_fish'),
        ('Fish burger patties', 'inactive', 'Value-added', 330, 0::numeric, 0.3::numeric, 0.68::numeric, 0.32::numeric, 1.1::numeric, 1.7::numeric, 0.55::numeric, null::text, 'full_fish'),
        ('Smoked fillet', 'inactive', 'Value-added', 340, 0::numeric, 0.38::numeric, 0.95::numeric, 0.05::numeric, 1.5::numeric, 2.2::numeric, 0.6::numeric, null::text, 'full_fish')
     ) as s(name, status, category, sort_order, glaze_pct, base_yield,
            pct_fish, pct_marinade, marinade_usd, process_usd, packing_usd,
            pack_size, basis)
where o.slug = 'oceanpick'
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- 7. Per-bucket yields — PLACEHOLDERS (Decisions §6)
--
-- Every bucket starts at the SKU's flat yield, so the table is usable from
-- day one and obviously still needs real data: while every bucket holds the
-- same number, switching buckets on changes only FCR and ODC, never yield.
-- Replace with the farm's yield at each bucket median.
-- ---------------------------------------------------------------------------
insert into demand_planner.cost_sku_bucket_yields (sku_id, bucket_id, yield_pct)
select s.id, b.id, s.base_yield
from demand_planner.cost_skus s
join demand_planner.cost_size_buckets b on b.org_id = s.org_id
on conflict (sku_id, bucket_id) do nothing;

-- ---------------------------------------------------------------------------
-- 8. Sanity check
-- ---------------------------------------------------------------------------
do $$
declare
  n_skus int;
  n_absorbed int;
begin
  select count(*) into n_skus
    from demand_planner.cost_skus s
    join demand_planner.organizations o on o.id = s.org_id
   where o.slug = 'oceanpick';
  select count(*) into n_absorbed
    from demand_planner.cost_skus s
    join demand_planner.organizations o on o.id = s.org_id
   where o.slug = 'oceanpick' and s.raw_material_basis = 'absorbed';
  if n_skus <> 34 then
    raise exception 'expected 34 costing SKUs, found %', n_skus;
  end if;
  if n_absorbed <> 6 then
    raise exception 'expected 6 absorbed by-product SKUs, found %', n_absorbed;
  end if;
end $$;
